### ISSUE TITLE
大佬，我项目中引入 van-weapp ，有些默认值组件创建后就没了，你有遇到过吗

### ISSUE THREAD

**Issue by lblblong** [Smi1e96/Taro3#1]
![image](https://user-images.githubusercontent.com/18625523/89483790-80f58e80-d7cf-11ea-9de0-150518f4b775.png)

比如 van-button 的 type 默认值本来是 default 的，我在它的 created 生命周期打印的时候 type 是 default，但是 attached 生命周期再打印就变成空字符串了
是不是 taro 做了什么默认值的覆盖啊

**Comment by lblblong** [comment]
而且我这边使用taro react 的时候，slot 也不支持

**Comment by Smi1e96** [comment]
> 而且我这边使用taro react的时候，slot也不支持

[使用slot](https://github.com/NervJS/taro/commit/dd636bddf4a65124afc996f9bdca55f3d5b8e66d)类似这样使用
![image](https://user-images.githubusercontent.com/31199247/89498776-806def80-d7f1-11ea-82ed-7ee44a871824.png)

**Comment by Smi1e96** [comment]
> ![image](https://user-images.githubusercontent.com/18625523/89483790-80f58e80-d7cf-11ea-9de0-150518f4b775.png)
> 
> 比如 van-button 的 type 默认值本来是 default 的，我在它的 created 生命周期打印的时候 type 是 default，但是 attached 生命周期再打印就变成空字符串了
> 是不是 taro 做了什么默认值的覆盖啊

你是不是有配置错误 
![image](https://user-images.githubusercontent.com/31199247/89499157-202b7d80-d7f2-11ea-8669-8e5ff9d6220d.png)
![image](https://user-images.githubusercontent.com/31199247/89499224-3a655b80-d7f2-11ea-9617-ff05406f7b38.png)
![image](https://user-images.githubusercontent.com/31199247/89499285-5668fd00-d7f2-11ea-9c3c-45fdc46fae6e.png)

**Comment by lblblong** [comment]
![image](https://user-images.githubusercontent.com/18625523/89500970-266f2900-d7f5-11ea-9642-35547f19122e.png)

大佬，直接拉你这个项目下来，default 是赋值上去了，但是 slot 没有生效

**Comment by Smi1e96** [comment]
这个项目是为了给taro官方提bug 创建的项目，所以你不太适合使用它:smile: 你要是想用这个项目 请把taro升级到最新版本3.0.7 你的问题就能解决， 3.0.7版本修复了很多第三方组件问题

**Comment by lblblong** [comment]
刚刚升级到 3.0.7 就直接跑不起来了😥

**Comment by Smi1e96** [comment]
哪里有问题？

**Comment by lblblong** [comment]
![image](https://user-images.githubusercontent.com/18625523/89509523-fed28d80-d801-11ea-9556-8fce3be2e212.png)
![image](https://user-images.githubusercontent.com/18625523/89509550-06923200-d802-11ea-9d63-3316131c85ed.png)
![image](https://user-images.githubusercontent.com/18625523/89509566-0b56e600-d802-11ea-9666-2164dae1aa4a.png)
![image](https://user-images.githubusercontent.com/18625523/89509585-13af2100-d802-11ea-9754-403dc7faea0a.png)


好像没改什么，就升级了一下版本就报错了

**Comment by Smi1e96** [comment]
删除dist 重新编译还是不可以吗？

**Comment by lblblong** [comment]
也不可以
而且我发现 van-weapp 里面有很多事件是横杠连接的
![image](https://user-images.githubusercontent.com/18625523/89510366-0f373800-d803-11ea-93c1-3e5b8c6e373e.png)
在 Taro 里，本来应该是用 onBeforeRead，但是没用，触发不到

**Comment by Smi1e96** [comment]
我建议你看下vant-weapp 源文件，文档和实际使用是不一样的 文档应该是合并vue版本过来的，现在这个项目只是为了提bug创建的,我现在的配置走 用得[这个](https://github.com/iiotjs/taro-dva) 如果使用这个 请下载下来使用 升级taro3.0.7
